name: build-for-land

on: workflow_dispatch

jobs:
  build-for-land:
    runs-on: ubuntu-latest
    steps:
      - name:
        run: |
          # Setting up Build Directories
          mkdir -p ~/android/lineage
          cd ~/android/lineage
          
          # Installing Dependencies from Apt
          sudo apt update && sudo apt install openjdk-8-jdk libwxgtk3.0-gtk3-dev bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev git repo
          
          # Authenticating "repo" with GitHub Account
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          
          # Enabling Caching (not sure)
          export USE_CCACHE=1
          export CCACHE_EXEC=/usr/bin/ccache
          ccache -M 25G
          
          # Setting Up Local Repo
          repo init -u https://github.com/LineageOS/android.git -b lineage-15.1 && repo sync
          
          #Now ensure your Redmi 3S/3X is connected to your computer via the USB cable, with ADB and root enabled, and that you are in the ~/android/lineage/device/xiaomi/land folder.
          #Then run the extract-files.sh script:
          #./extract-files.sh
          #The blobs should be pulled into the ~/android/lineage/vendor/xiaomi folder. If you see “command not found” errors, adb may need to be placed in ~/bin.
          
          # Setting Up Build Environment
          source build/envsetup.sh && breakfast land
          
          # Starting Build Process
          #croot && brunch land
          
          # Build Finished
          #cd $OUT
